
  export const ProjectData = [
    {
      id: 1,
      title: " Personal Portfolio Website with Next.js",
      des: "A clean and modern portfolio website built with Next.js to showcase projects and skills. Fully responsive, featuring smooth animations and easy navigation.",
      img: "/p1.png",
      iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/fm.svg"],
      link: "https://xashadulpo-portfolio.vercel.app",
    },
    {
      id: 2,
      title: "Animated Apple Iphone 3D Website",
      des: "Recreated the Apple iPhone 15 Pro website, combining GSAP animations and Three.js 3D effects..",
      img: "/p2.png",
      iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
      link: "https://iphone-nu.vercel.app",
    },
    {
      id: 3,
      title: "Ethereum Transaction dApp",
      des: " A decentralized application that allows users to connect their MetaMask wallet, send ETH, and view transaction history. Built using Next.js, ethers.js, and Solidity",
      img: "/p3.png",
      iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/c.svg"],
      link: "https://send-eth-test-project.vercel.app",
    },
    {
      id: 4,
      title: "Car Showroom Showcase",
      des: "A sleek website where users can search and explore their favorite cars with advanced filtering options. Featuring a modern UI for a seamless car browsing experience.",
      img: "/p4.png",
      iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
      link: "https://carhub-neon.vercel.app",
    }, 
    {
      id: 5,
      title: " Amazon Clone",
      des: "A fully responsive e-commerce platform replicating Amazon's features, including product browsing, cart management, and checkout. Built with modern web technologies for a smooth shopping experience.",
      img: "/p5.png",
      iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
      link: "https://amazon-gamma-rust.vercel.app",
    },
    {
      id: 6,
      title: " Digital Banking App",
      des: "A simple online banking platform where users can add funds, view their account balance, and manage transactions securely. Built for a seamless banking experience.",
      img: "/p6.png",
      iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
      link: "https://bank-liard-eight.vercel.app",
    },
    {
      id: 7,
      title: "Business Client Portfolio",
      des: "An elegant and dynamic portfolio platform built for business professionals. Features smooth GSAP animations, responsive layouts, and a seamless user experience — designed to impress clients and showcase work beautifully.",
      img: "/p7.png",
      iconLists: [
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gsap/gsap-original.svg",
      ],
      link: "https://deshit-seven.vercel.app/",
    },
    {
      id: 8,
      title: "NFT Marketplace",
      des: "A next-generation NFT trading platform where users can mint, buy, and sell digital assets. Built with Next.js, Tailwind, TypeScript, MongoDB, GraphQL, WebSocket, and Solidity — a complete full-stack Web3 experience.",
      img: "/p8.png",
      iconLists: [
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/solidity/solidity-original.svg",
      ],
      link: "https://leox-multi.vercel.app/",
    },
    {
      id: 9,
      title: "Spectrum ICO DApp",
      des: "A decentralized ICO platform that allows users to join live token presales, connect MetaMask wallets, and purchase tokens securely on Ethereum. Powered by Next.js, Solidity, and Web3.js for a transparent DeFi experience.",
      img: "/p9.png",
      iconLists: [
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ethereum/ethereum-original.svg",
        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/solidity/solidity-original.svg",
      ],
      link: "https://spectum-dapp.vercel.app/",
    }
    
  ];